let products = {
    1000: {
        product_name: "Limón con semilla",
        product_price: 1.28,
        image_url: "./images/Name=Limon.jpg",
        add: false,
        discount: true,
        prod_id: 1000,
    },
    1001: {
        product_name: "Tomate",
        product_price: 1.21,
        image_url: "./images/Name=Tomate.jpg",
        add: false,
        discount: true,
        prod_id: 1001,
    },
    1002: {
        product_name: "Aguacate Hass",
        product_price: 2.44,
        image_url: "./images/Name=Aguacate.jpg",
        add: false,
        discount: true,
        prod_id: 1002,
    },
    1003: {
        product_name: "Nopal",
        product_price: 1.67,
        image_url: "./images/Name=Nopal.jpg",
        add: false,
        discount: true,
        prod_id: 1003,
    },
    1004: {
        product_name: "Tomate verde",
        product_price: 1.22,
        image_url: "./images/Name=Tomate verde.jpg",
        add: false,
        discount: true,
        prod_id: 1004,
    },
    1005: {
        product_name: "Cocacola",
        product_price: 1.24,
        image_url: "./images/Name=Cocacola.jpg",
        add: false,
        discount: true,
        prod_id: 1005,
    },
    1006: {
        product_name: "Cocacola sin azucar",
        product_price: 1.28,
        image_url: "./images/Name=Cocacola sin azucar.jpg",
        add: false,
        discount: true,
        prod_id: 1006,
    },
    1007: {
        product_name: "Manzana Golden",
        product_price: 2.00,
        image_url: "./images/Name=Manzana Golden.jpg",
        add: false,
        discount: true,
        prod_id: 1007,
    },



    1008: {
        product_name: "Pechuga de pavo",
        product_price: 8.77,
        image_url: "./images/Name=Pechuga de pavo.jpg",
        add: false,
        discount: false,
        prod_id: 1008,
    },
    1009: {
        product_name: "Pan Bimbo",
        product_price: 1.86,
        image_url: "./images/Name=Pan Bimbo.jpg",
        add: false,
        discount: false,
        prod_id: 1009,
    },
    1010: {
        product_name: "Mc Cormick Mayonesa",
        product_price: 2.35,
        image_url: "./images/Name=Mc Cormick Mayonesa.jpg",
        add: false,
        discount: false,
        prod_id: 1010,
    },
    1011: {
        product_name: "Pasta Colgate",
        product_price: 1.68,
        image_url: "./images/Name=Colgate.jpg",
        add: false,
        discount: false,
        prod_id: 1011,
    },
    1012: {
        product_name: "Huevos San Juan",
        product_price: 1.85,
        image_url: "./images/Name=Huevos.jpg",
        add: false,
        discount: false,
        prod_id: 1012,
    },
    1013: {
        product_name: "Naranja",
        product_price: 1.20,
        image_url: "./images/Name=Naranja.jpg",
        add: false,
        discount: false,
        prod_id: 1013,
    },
    1014: {
        product_name: "Fabuloso",
        product_price: 1.77,
        image_url: "./images/Name=Fabuloso.jpg",
        add: false,
        discount: false,
        prod_id: 1014,
    },
    1015: {
        product_name: "Jitomates",
        product_price: 1.95,
        image_url: "./images/Name=Jitomate Bola.jpg",
        add: false,
        discount: false,
        prod_id: 1015,
    },
    
}
